apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: {{ .Values.namespace }}
  labels:
    app: laravel-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      initContainers:
        - name: copy-public
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c", "cp -r /var/www/html/public/. /shared/"]
          volumeMounts:
            - name: app-public
              mountPath: /shared

      containers:
        - name: php-fpm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.phpFpm | nindent 12 }}

        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: app-public
              mountPath: /var/www/html/public
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: app-public
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: laravel-app
  ports:
    - port: 8123
      targetPort: 80
  type: ClusterIP
