apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.dbDatabase | quote }}
  POSTGRES_USER: {{ .Values.secrets.dbUsername | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  APP_KEY: {{ printf "base64:%s" (randAlphaNum 32 | b64enc) }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
